# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Jukebox iOS' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jukebox iOS
  pod "XCDYouTubeKit", "~> 2.5"
  pod "Alamofire", "~> 3.4"
end

target 'Jukebox macOS' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jukebox macOS
  pod "XCDYouTubeKit", "~> 2.5"
  pod "Alamofire", "~> 3.4"
end
